### PR TITLE
Switch to GitLab CI

### PR DESCRIPTION
**Pull request by dewyatt**

### CODE REVIEW

**Comment by dewyatt** [comment]
@ronaldtse @ribose-jeffreylau CI is going to fail for the following repos:
* rpm-spec-rbenv-ruby-2.3.4
* rpm-spec-rbenv-ruby-2.4.3
* rpm-spec-rbenv-ruby-2.5.0

Apparently when you import from GitHub, GitLab defaults to converting periods to hyphens in the name.
Can someone with permissions correct this?

If you go to:

https://gitlab.com/ribose/rpm-spec-rbenv-ruby-2-3-4/edit
https://gitlab.com/ribose/rpm-spec-rbenv-ruby-2-4-3/edit
https://gitlab.com/ribose/rpm-spec-rbenv-ruby-2-5-0/edit

Expand the `Advanced` section, scroll to the `Rename repository` section, then:
1. Fix the `Project name` (example: `rpm-spec-rbenv-ruby-2-3-4` to `rpm-spec-rbenv-ruby-2.3.4`)
2. Fix the `Path` field (as above)

I *could* fix this in the .gitlab-ci.yml for each of these repos, but it seems cleaner to do it this way.

**Comment by ribose-jeffreylau** [comment]
@dewyatt  Good call!  I've renamed the projects and also hit "Retry" on the GitLab CI pipelines.  Thanks!

**Comment by ribose-jeffreylau** [comment]
Also just renamed the project paths to match the project names. 👌

**Comment by dewyatt** [comment]
Thanks @ribose-jeffreylau !

**Pull request merged**
